config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def new #untuk menampilkan form data baru
      @exam = Exam.new
    end
  
    def create #untuk memproses data baru yang dimasukan di form new
      #render plain: params.inspect cara mengecek apa isi params
      #title = params [:book][:title] cara mngecek balikan params
      exam = Exam.new(resource_params)
      exam.save 
      flash[:notice] = 'Exam has been created'
      redirect_to exams_path
    end
  
    def edit #menampilkan data yang sudah disimpan di edit
      id = params[:id]
      @exam = Exam.find(id)
    end
  
    def update #melakuka prses ketika user mengedit data
      id = params[:id]
      @exam = Exam.find(params[:id])
      @exam.update(resource_params)
      flash[:notice] = 'Exam has been update'
        redirect_to exams_path(@exam)
      
    end
  
    def destroy #untuk menghapus data
       id = params[:id]
       exam = Exam.find(params[:id])
       exam.destroy
       flash[:notice] = 'Exam has been delete'
       redirect_to exams_path
    end
  
    def index #menampilkan seluruh data yang ada di database
      @exams = Exam.all
    end
  
    def show #menampilkan sebuah data secara detail
      id = params[:id]
      @exam = Exam.find (id)
      # render plain : id
      # render plain : @book.title
  
    end
  private
  def resource_params
    params.require(:exam).permit(:title, :mapel, :duration, :nilai, :status, :level, :student_id)
  end
  end
  

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new #untuk menampilkan form data baru
      @payment = Payment.new
    end
  
    def create #untuk memproses data baru yang dimasukan di form new
      #render plain: params.inspect cara mengecek apa isi params
      #title = params [:book][:title] cara mngecek balikan params
      payment = Payment.new(resource_params)
      payment.save 
      flash[:notice] = 'Payment has been created'
      redirect_to payments_path
    end
  
    def edit #menampilkan data yang sudah disimpan di edit
      id = params[:id]
      @payment = Payment.find(id)
    end
  
    def update #melakuka prses ketika user mengedit data
      id = params[:id]
      @payment = Payment.find(params[:id])
      @payment.update(resource_params)
      flash[:notice] = 'Payment has been update'
        redirect_to payments_path(@payment)
      
    end
  
    def destroy #untuk menghapus data
       id = params[:id]
       payment = Payment.find(params[:id])
       payment.destroy
       flash[:notice] = 'Payment has been delete'
       redirect_to payments_path
    end
  
    def index #menampilkan seluruh data yang ada di database
      @payments = Payment.all
    end
  
    def show #menampilkan sebuah data secara detail
      id = params[:id]
      @payment = Payment.find (id)
      # render plain : id
      # render plain : @book.title
  
    end
  private
  def resource_params
    params.require(:payment).permit(:id_transaction, :status, :upload)
  end
  end
  

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    def new #untuk menampilkan form data baru
      @report = Report.new
    end
  
    def create #untuk memproses data baru yang dimasukan di form new
      #render plain: params.inspect cara mengecek apa isi params
      #title = params [:book][:title] cara mngecek balikan params
      report = Report.new(resource_params)
      report.save 
      flash[:notice] = 'Report has been created'
      redirect_to reports_path
    end
  
    def edit #menampilkan data yang sudah disimpan di edit
      id = params[:id]
      @report = Report.find(id)
    end
  
    def update #melakuka prses ketika user mengedit data
      id = params[:id]
      @report = Report.find(params[:id])
      @report.update(resource_params)
      flash[:notice] = 'Report has been update'
        redirect_to reports_path(@report)
      
    end
  
    def destroy #untuk menghapus data
       id = params[:id]
       report = Report.find(params[:id])
       report.destroy
       flash[:notice] = 'Report has been delete'
       redirect_to reports_path
    end
  
    def index #menampilkan seluruh data yang ada di database
      @reports = Report.all
    end
  
    def show #menampilkan sebuah data secara detail
      id = params[:id]
      @report = Report.find (id)
      # render plain : id
      # render plain : @book.title
  
    end
  private
  def resource_params
    params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :level)
  end
  end
  

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def new #untuk menampilkan form data baru
      @student = Student.new
    end
  
    def create #untuk memproses data baru yang dimasukan di form new
      #render plain: params.inspect cara mengecek apa isi params
      #title = params [:book][:title] cara mngecek balikan params
      student = Student.new(resource_params)
      student.save 
      flash[:notice] = 'Student has been created'
      redirect_to students_path
    end
  
    def edit #menampilkan data yang sudah disimpan di edit
      id = params[:id]
      @student = Student.find(id)
    end
  
    def update #melakuka prses ketika user mengedit data
      id = params[:id]
      @student = Student.find(params[:id])
      @student.update(resource_params)
      flash[:notice] = 'Student has been update'
        redirect_to students_path(@student)
      
    end
  
    def destroy #untuk menghapus data
       id = params[:id]
       student = Student.find(params[:id])
       student.destroy
       flash[:notice] = 'student has been delete'
       redirect_to students_path
    end
  
    def index #menampilkan seluruh data yang ada di database
      @students = Student.all
    end
  
    def show #menampilkan sebuah data secara detail
      id = params[:id]
      @student = Student.find (id)
      # render plain : id
      # render plain : @book.title
  
    end
  private
  def resource_params
    params.require(:student).permit(:name, :username, :age, :rombel, :address, :city, :nik)
  end
  end
  

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def new #untuk menampilkan form data baru
      @teacher = Teacher.new
    end
  
    def create #untuk memproses data baru yang dimasukan di form new
      #render plain: params.inspect cara mengecek apa isi params
      #title = params [:book][:title] cara mngecek balikan params
      teacher = Teacher.new(resource_params)
      teacher.save 
      flash[:notice] = 'Teacher has been created'
      redirect_to teachers_path
    end
  
    def edit #menampilkan data yang sudah disimpan di edit
      id = params[:id]
      @teacher = Teacher.find(id)
    end
  
    def update #melakuka prses ketika user mengedit data
      id = params[:id]
      @teacher = Teacher.find(params[:id])
      @teacher.update(resource_params)
      flash[:notice] = 'Teacher has been update'
        redirect_to teachers_path(@teacher)
      
    end
  
    def destroy #untuk menghapus data
       id = params[:id]
       teacher = Teacher.find(params[:id])
       teacher.destroy
       flash[:notice] = 'teacher has been delete'
       redirect_to teachers_path
    end
  
    def index #menampilkan seluruh data yang ada di database
      @teachers = Teacher.all
    end
  
    def show #menampilkan sebuah data secara detail
      id = params[:id]
      @teacher = Teacher.find (id)
      # render plain : id
      # render plain : @book.title
  
    end
  private
  def resource_params
    params.require(:teacher).permit(:nik, :nama, :age, :kelas, :mapel)
  end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/destroy.html.erb
<%= form_for (@exam) do |f| %>
<%= f.label :title %> </br>
<%= f.text_field :title %> </br>

<%= f.label :mapel %> </br>
<%= f.text_field :mapel %> </br>

<%= f.label :duration %> </br>
<%= f.text_field :duration %> </br>

<%= f.label :nilai %> </br>
<%= f.text_field :nilai %> </br>

<%= f.label :status %> </br>
<%= f.text_field :status %> </br>

<%= f.label :level %> </br>
<%= f.text_field :level %> </br>

<%= f.label :student_id %> </br>
<%= f.text_field :student_id %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/exams/edit.html.erb
<%= form_for (@exam) do |f| %>
<%= f.label :title %> </br>
<%= f.text_field :title %> </br>

<%= f.label :mapel %> </br>
<%= f.text_field :mapel %> </br>

<%= f.label :duration %> </br>
<%= f.text_field :duration %> </br>

<%= f.label :nilai %> </br>
<%= f.text_field :nilai %> </br>

<%= f.label :status %> </br>
<%= f.text_field :status %> </br>

<%= f.label :level %> </br>
<%= f.text_field :level %> </br>

<%= f.label :student_id %> </br>
<%= f.text_field :student_id %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/exams/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container"><table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Mapel</th>
        <th>Duration</th>
        <th>Nilai</th>
        <th>Status</th>
        <th>Level</th>
        <th>Student ID</th>
        <th>Action</th>
    </tr>
    </thead>    <tbody>
    <% @exams.each do |exam| %>
    <tr>
        <td><%= exam.title %></td>
        <td><%= exam.mapel %></td>
        <td><%= exam.duration %></td>
        <td><%= exam.nilai %></td>
        <td><%= exam.status %></td>
        <td><%= exam.level %></td>
        <td><%= exam.student_id %></td>
        

        <td>
       
        <%= link_to 'Detail', exam_path(exam), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_exam_path(exam), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', exam_path(exam) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>    </tr>
    <% end %>
    </tbody></table> 
<%= link_to 'New Exam', new_exam_path(), class:"btn btn-primary" %><!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/exams/new.html.erb
<%= form_for (@exam) do |f| %>
<%= f.label :title %> </br>
<%= f.text_field :title %> </br>

<%= f.label :mapel %> </br>
<%= f.text_field :mapel %> </br>

<%= f.label :duration %> </br>
<%= f.text_field :duration %> </br>

<%= f.label :nilai %> </br>
<%= f.text_field :nilai %> </br>

<%= f.label :status %> </br>
<%= f.text_field :status %> </br>

<%= f.label :level %> </br>
<%= f.text_field :level %> </br>

<%= f.label :student_id %> </br>
<%= f.text_field :student_id %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>


title : <%= @exam.title %> </br>
mapel : <%= @exam.mapel %> </br>
title : <%= @exam.title %> </br>
mapel : <%= @exam.mapel %> </br>

<%= link_to 'kembali ke halaman sebelumnya',exams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kejarr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/destroy.html.erb
<%= form_for (@payment) do |f| %>
<%= f.label :id_transaction %> </br>
<%= f.text_field :id_transaction %> </br>

<%= f.label :status %> </br>
<%= f.text_field :status %> </br>

<%= f.label :upload %> </br>
<%= f.text_field :upload %> </br>


<%= f.submit "Save" %> 
<% end %>

app/views/payments/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container"><table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>ID Transaction</th>
        <th>Status</th>
        <th>Upload</th>
        <th>Action</th>
    </tr>
    </thead>    <tbody>
    <% @payments.each do |payment| %>
    <tr>
        <td><%= payment.id_transaction %></td>
        <td><%= payment.status %></td>
        <td><%= payment.upload %></td>
        <td>
        <%= link_to 'Detail', payment_path(payment), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_payment_path(payment), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', payment_path(payment) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>    </tr>
    <% end %>
    </tbody></table> 
<%= link_to 'New Payment', new_payment_path(), class:"btn btn-primary" %><!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/reports/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container"><table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Hasil</th>
        <th>Mapel</th>
        <th>Teacher ID</th>
        <th>Student ID</th>
        <th>Date</th>
        <th>Action</th>
    </tr>
    </thead>    <tbody>
    <% @reports.each do |report| %>
    <tr>
        <td><%= report.title %></td>
        <td><%= report.hasil %></td>
        <td><%= report.mapel %></td>
        <td><%= report.teacher_id %></td>
        <td><%= report.student_id %></td>
        <td><%= report.date %></td>
        <td>
        <%= link_to 'Detail', report_path(report), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_report_path(report), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', report_path(report) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>    </tr>
    <% end %>
    </tbody></table> 
<%= link_to 'New Report', new_report_path(), class:"btn btn-primary" %><!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/students/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container"><table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Name</th>
        <th>Username</th>
        <th>Rombel</th>
        <th>Kelas</th>
        <th>Address</th>
        <th>City</th>
        <th>NIK</th>
        <th>Action</th>
    </tr>
    </thead>    <tbody>
    <% @students.each do |student| %>
    <tr>
        <td><%= student.name %></td>
        <td><%= student.username %></td>
        <td><%= student.age %></td>
        <td><%= student.rombel %></td>
        <td><%= student.address %></td>
        <td><%= student.city %></td>
        <td><%= student.nik %></td>
        <td>
        <%= link_to 'Detail', student_path(student), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_student_path(student), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', student_path(student) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>    </tr>
    <% end %>
    </tbody></table> 
<%= link_to 'New Student', new_student_path(), class:"btn btn-primary" %><!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>

app/views/teachers/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container"><table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>NIK</th>
        <th>Nama</th>
        <th>Age</th>
        <th>Rombel</th>
        <th>Mapel</th>
         <th>Action</th>
       
    </tr>
    </thead>    <tbody>
    <% @teachers.each do |teacher| %>
    <tr>
        <td><%= teacher.nik %></td>
        <td><%= teacher.nama %></td>
        <td><%= teacher.age %></td>
        <td><%= teacher.rombel %></td>
        <td><%= teacher.mapel %></td>
        <td>
        <%= link_to 'Detail', teacher_path(teacher), class:"btn btn-outline-secondary" %> 
        <%= link_to 'Edit', edit_teacher_path(teacher), class:"btn btn-outline-warning" %> 
        <%= link_to 'Delete', teacher_path(teacher) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>    </tr>
    <% end %>
    </tbody></table> 
<%= link_to 'New Teacher', new_teacher_path(), class:"btn btn-primary" %><!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
</div>